'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageAccountsHomepage

    '''<summary>
    '''lnkManageYourOwnEmpAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkManageYourOwnEmpAccount As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkManageCustomerAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkManageCustomerAccount As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkManageAnEmployeeAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkManageAnEmployeeAccount As Global.System.Web.UI.WebControls.LinkButton
End Class
